apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: signalement
type: Opaque
stringData:
  # Remplacer les valeurs par les vraies credentials en production
  # Ces valeurs seront injectées par le pipeline CD via kubectl create secret
  datasource-url: "jdbc:mysql://mysql-service:3306/signalementDb?createDatabaseIfNotExist=true&serverTimezone=UTC"
  datasource-username: "admin"
  datasource-password: "admin123"
