apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: signalement
type: Opaque
stringData:
  datasource-url: "jdbc:mysql://mysql-service:3306/signalementDb?createDatabaseIfNotExist=true&serverTimezone=UTC"
  datasource-username: "admin"
  datasource-password: "admin123"
